### ISSUE TITLE
Create a contributing.md file for new contributors

### ISSUE THREAD

**Issue by Amishakumari544** [oras-project/oras-www#100]
As of now we don't have any `[CONTRIBUTING.md]` file for new comers.

**Comment by Amishakumari544** [comment]
I would like to add this file in the repo. @FeynmanZhou

**Comment by TerryHowe** [comment]
https://github.com/oras-project/oras-www/pull/90

**Comment by Amishakumari544** [comment]
ok @TerryHowe  but it doesn't contains
Add a reference(remote) to the original repository.
`git remote add upstream https://github.com/oras-project/oras-www.git`

- Check the remotes for this repository.
- Always take a pull from the upstream repository to your master branch to keep it at par with the main project (updated repository).
- Create a new branch.

**Comment by TerryHowe** [comment]
Here is the PR to add the `CONTRIBUTING.md` to the oras repository https://github.com/oras-project/oras/pull/781. If #90 merges, something like that maybe? The extra steps you bring up are good ones, but not sure how others would feel.

**Comment by TerryHowe** [comment]
Creating an upstream repository on your local is just a possible procedure.  I don't think we want to tell people how they should use git.
