### ISSUE TITLE
create active oras maintainers page

### ISSUE THREAD

**Issue by Amishakumari544** [oras-project/oras-www#104]
As I was looking in one of the PR where the contributor was not aware of the oras project maintainers.
I proposed to create an active `maintainer file` to help the new folks not to tag everyone instead only the oras maintainers for the PR reviews.

**Comment by TerryHowe** [comment]
other than the OWNERS.md?

**Comment by Amishakumari544** [comment]
@FeynmanZhou what do you think?
@TerryHowe  you are not a maintainer but you are active please give the good direction 🙂

**Comment by Amishakumari544** [comment]
> other than the OWNERS.md?

they all are the active maimtainers here? If yes then it's not necessary .
