### ISSUE TITLE
Add links section for further reading

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras-www#11]
Add a section at the bottom of the homepage with a list of links to explain OCI Artifacts etc. further

**Comment by eniolajayi** [comment]
Hello 👋 @dtzar Can I help help out with this issue, if it has not been tackled yet. I can start by researching good links to include in the section and run them by you.

**Comment by Asmit2952** [comment]
I think this issue can be worked upon after the documentation migration.

**Comment by eniolajayi** [comment]
Noted
Any update or info on when the new documentation will be available?

**Comment by Asmit2952** [comment]
It might be done during LFX Mentorship 2023 term.

**Comment by TerryHowe** [comment]
Based on the detail in this issue, https://oras.land/docs/concepts/artifact should cover this.
