### ISSUE TITLE
Enforce branch policies on this repository

### ISSUE THREAD

**Issue by toddysm** [oras-project/oras-www#123]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

To improve the security of the ORAS project we need to enforce the branch policies for this repository. I propose that we enforce the policies as follows:

- Use the following rules for `main` and `release/*` branches:
    - Require PR before merging
      - [ ] Require 3 approvals
      - [x] Dismiss stale PR approvals when new commits are pushed
      - [x] Require review from Code Owners
      - [x] Require status checks to pass before merging
      - [x] Require conversation resolution before merging
      - [x] Require signed commits
      - [x] Do not allow bypass the above settings

Please add your comments and proposals for additional changes to this issue.

### Additional comments?

N/A

**Comment by TerryHowe** [comment]
I think we should leave this on 2 approvers. Security is less of an issue here.
