### ISSUE TITLE
Document how to show the content downloading progress with pv

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#130]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

Currently, ORAS doesn't have a progress bar yet, it is possible to show the content downloading progress with `jq` and `pv`. Here's an example:

```
$ blob_ref=ghcr.io/oras-project/oras@sha256:74529e03eae02d1fff5c05e9a6ec2089e1f5ae96421169c29a7c165346e042e4
$ size=$(oras blob fetch --descriptor $blob_ref | jq -r .size)
$ oras blob fetch $blob_ref --output - | pv -s $size > layer.bin
1.58MiB 0:00:03 [1.47MiB/s] [================================>                                         ] 45% ETA 0:00:03
```

We need to add this trick to ORAS documentation.

**Comment by RickDeb2004** [comment]
Closes: #130
This pull request Resolves Issue: #180 
updated oras_blob_fetch.mdx
