### ISSUE TITLE
add document for escaping file references in oras CLI

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-www#134]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

oras CLI uses colon `:` as a delimiter of file path and media type in the file reference. If a file reference 1) doesn't contain mediatype and 2) file path contains colon, user should add colon at the end of reference.

```
# file path: my.file
# media type: file.media.type
oras push $REG/$REPO:$TAG my.file:file.media.type


# file path: my:file
# media type:N/A
oras push $REG/$REPO:$TAG my:file:
```

### Additional comments?

This should be documented in oras.land so oras user can find it.

**Comment by TerryHowe** [comment]
Going to close https://github.com/oras-project/oras/pull/734 ?
