### ISSUE TITLE
Add the installation instruction for NixOS

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#135]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

ORAS has a NixOS package which will be upgraded to ORAS v1.0.0, see https://github.com/NixOS/nixpkgs/pull/222341

We need to add the installation instruction for NixOS at https://oras.land/cli/ after the PR https://github.com/NixOS/nixpkgs/pull/222341 is merged.

**Comment by developer-guy** [comment]
I'm willing to do this, would you mind assigning it to me ☝️
