### ISSUE TITLE
Proposal: creating a new branch for migration of the website

### ISSUE THREAD

**Issue by asmitbm** [oras-project/oras-www#138]
Hello everyone.

I'm an LFX Mentee for [CNCF - ORAS: Develop ORAS Website](https://mentorship.lfx.linuxfoundation.org/project/7f633ade-64f5-477c-bcbe-7b6693329c63). This is the current issue: #82 I am working on.

I'd like to create a new branch (`website-migration`) for ORAS website migration, as suggested in today's meeting. Until the website has been completely migrated, all of my commits will be pushed to this new branch.

Here's the preview of this website: https://orasland.netlify.app/
and here's the repository I am maintaining: https://github.com/asmitbm/oras-website

It will also be helpful if I have [write access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization) (not maintainer role) to this repository so that I can make quick design changes and add/remove features, which will allow me to stay on track with the LFX timeline. All of my commits will be on the `website-migration` branch until it is merged with `main`.

Cc: @FeynmanZhou

**Comment by FeynmanZhou** [comment]
@asmitbm I created a `dev` branch for your migration. You can submit a PR to request merge your changes to this dev branch first: https://github.com/oras-project/oras-www/tree/dev

**Comment by FeynmanZhou** [comment]
Close this issue since the dev branch was created for staging env
