### ISSUE TITLE
oras go module redirect configuration issues

### ISSUE THREAD

**Issue by asmitbm** [oras-project/oras-www#141]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

The current https://oras.land/ website handles oras-go redirects. 

* https://oras.land/oras-credentials-go/
* https://oras.land/oras-go/
* https://oras.land/oras/

Any documentation changes breaks the code. There might be multiple ways to approach this problem, which were discussed in the meeting:

* Using GitHub as the source, since the links on oras.land redirects to respective modules on GitHub
* Using [Netlify Redirects](https://docs.netlify.com/routing/redirects/)
* Include redirects in the new website

Take a look at this [comment](https://github.com/oras-project/oras-www/pull/140#pullrequestreview-1380245233) in PR: #140,

**Comment by FeynmanZhou** [comment]
Hi Asmit, we investigated Docusaurus configuration today. 

It seems we need to write a page to define the head metadata in the `dev` branch by following this [guide](https://docusaurus.io/docs/markdown-features/head-metadata) and reuse the redirect configuration from https://github.com/oras-project/oras-www/blob/main/docs/custom/main.html.

Would you be able to take a look and add this head metadata to a new page? This page should be invisible to users.

**Comment by asmitbm** [comment]
> Hi Asmit, we investigated Docusaurus configuration today.
> 
> It seems we need to write a page to define the head metadata in the `dev` branch by following this [guide](https://docusaurus.io/docs/markdown-features/head-metadata) and reuse the redirect configuration from https://github.com/oras-project/oras-www/blob/main/docs/custom/main.html.
> 
> Would you be able to take a look and add this head metadata to a new page? This page should be invisible to users.

I think 4 new pages would be required then? According to different modules. The old website also has different pages for redirects if I am not wrong.

**Comment by asmitbm** [comment]
Also I researched on Netlify's redirects and I don't think that's one of the solutions which we are looking for. According to this [official blog post](https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/), Netlify's redirects used when a user types in a specific URL or clicks on a link that leads to an old or outdated page, they will automatically be redirected to a new and updated page. This feature is useful for maintaining the integrity of a website's content and ensuring that visitors are always able to find the information they are looking for.

**Comment by FeynmanZhou** [comment]
@asmitbm You are right. We need 3 new pages for redirects but they should be invisible to users. This link https://oras.land/oras-credentials-go/ is not needed for the new website.

**Comment by FeynmanZhou** [comment]
Close this issue since it was done by #146
