### ISSUE TITLE
Logo refresh?

### ISSUE THREAD

**Issue by bridgetkromhout** [oras-project/oras-www#15]
Hi, folks! We have an existing logo in https://github.com/oras-project/oras-www/blob/main/docs/assets/images/oras.png. According the info at https://www.cncf.io/services-for-projects/#design-and-aesthetics we can request a logo refresh by CNCF if desired. Do we want to do so? Let's figure that out.

**Comment by bridgetkromhout** [comment]
CNCF provided a better SVG of the single existing design, as discussed in https://github.com/cncf/landscape/pull/2290#issuecomment-927972738.

**Comment by SteveLasker** [comment]
@bridgetkromhout, the [logo at merged](https://github.com/bridgetkromhout/cncf-landscape/blob/a95f087a9ed1c5239a7f45228844fab2ffd5ff32/hosted_logos/oras.svg) from cncf/landscape#2290 (comment). looks great. Is there additional action needed here?

**Comment by bridgetkromhout** [comment]
Hi, Steve - what we have now is very limited and doesn't match the typical project. as explained in https://github.com/cncf/artwork#cncf-logos - "We prepare artwork in 2 formats (PNG & SVG), 3 layouts -- horizontal (also known as landscape format), stacked (which is closer to square), and icon (which does not include the name and is square), and at least 3 versions (color/black/white)"

Compare what we have for ORAS: https://github.com/cncf/artwork/blob/master/examples/sandbox.md#oras-logos
To something like Krustlet: https://github.com/cncf/artwork/blob/master/examples/sandbox.md#krustlet-logos

CNCF is willing to work with the team to create the missing versions. Do we want that?

**Comment by SteveLasker** [comment]
Ahh, yes. That makes sense. Yes, please.

**Comment by bridgetkromhout** [comment]
Closing this as it seems not to be necessary to make further logo changes, over the last several years. Thanks.
