### ISSUE TITLE
Use dependabot to track dependency update

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-www#152]
Some dependencies in [package.json](https://github.com/oras-project/oras-www/blob/main/package.json) is outdated but never notified or updated. We can introduce dependabot to improve that.

**Comment by FeynmanZhou** [comment]
@asmitbm Could you take a look at this issue? I think introducing a Dependabot is necessary.

**Comment by asmitbm** [comment]
> @asmitbm Could you take a look at this issue? I think introducing a Dependabot is necessary.

Yupp will look into this issue today!

**Comment by asmitbm** [comment]
Hey @FeynmanZhou, I looked at the docs today and it seems like maintainers should enable dependabot in the repository. Here's the guide: https://docs.github.com/en/code-security/dependabot/dependabot-alerts/configuring-dependabot-alerts
Once, default settings are enabled, then I can configure it properly according to project needs.

**Comment by FeynmanZhou** [comment]
> Hey @FeynmanZhou, I looked at the docs today and it seems like maintainers should enable dependabot in the repository. Here's the guide: https://docs.github.com/en/code-security/dependabot/dependabot-alerts/configuring-dependabot-alerts Once, default settings are enabled, then I can configure it properly according to project needs.

Okay, I will enable that configuration. Thanks.

**Comment by RickDeb2004** [comment]
Closes: https://github.com/oras-project/oras-www/issues/152
This pull request Resolves Issue https://github.com/oras-project/oras-www/issues/152
Added dependabot.yml
