### ISSUE TITLE
Typos in Docs

### ISSUE THREAD

**Issue by SD-13** [oras-project/oras-www#182]
### Page URL

1. https://oras.land/docs/cli/pushing/#pushing-artifacts-with-config-files
2. https://oras.land/docs/CLI/pulling

### User feedback

1. Push an the artifact  -->  Push an artifact / Push the artifact
2. oras pull localhost:5000/hello-artifact:v2 -a  -->  oras pull localhost:5000/hello-artifact:v2

**Comment by TerryHowe** [comment]
Were you going to follow up with a PR?

**Comment by SD-13** [comment]
@TerryHowe yeah. I was waiting for one of the members response. Will create a PR tonight. Thanks!
