### ISSUE TITLE
[Documentation Feedback]: slack link is not working

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-www#189]
### Page URL

https://oras.land/docs/contributing/#contact-us

### User feedback

I found that the CNCF slack link (https://cloud-native.slack.com/) is not working, but I can get the invite email via https://slack.cncf.io/. Do we need to update the link?

**Comment by qweeah** [comment]
> https://cloud-native.slack.com/

@TerryHowe Tried with an unregistered email. This link also ends with an email saying `It looks like there isn’t an account on Cloud Native Computing Foundation tied to this email address.`. But https://slack.cncf.io/ does provide a link to join the workspace. @FeynmanZhou Is the doc intended to provide such facility? If so, we need to update the link.

**Comment by qweeah** [comment]
BTW https://slack.cncf.io/ resolves to https://communityinviter.com/apps/cloud-native/cncf, which looks like a real invite link.

**Comment by deepeshaburse** [comment]
> I think the sequence is to join the CNCF Slack workspace from https://slack.cncf.io/ and then enter the #oras slack channel via https://cloud-native.slack.com/archives/CJ1KHJM5Z. This should be reminded in the ORAS documentation. 
> 
> 
> 
> @deepeshaburse Would you mind taking this issue and providing a friendly guideline to tell new folks to join the Slack channel? 

@FeynmanZhou definitely 👍🏼
