### ISSUE TITLE
[Add adopter]: Gitlab

### ISSUE THREAD

**Issue by pdecat** [oras-project/oras-www#192]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What is the name of your project/registry?

Gitlab :)

Not the maintainer of the project, just a user.

### Link of your project/registry

https://gitlab.com/

https://docs.gitlab.com/ee/user/packages/container_registry/#supported-image-types

### Link of your project's/registry's SVG

https://about.gitlab.com/images/press/logo/svg/gitlab-logo-500.svg

From https://about.gitlab.com/press/press-kit/

### Additional comments?

Already recognized as an adopter in https://github.com/distribution/distribution/blob/87b280718d3898c8c78ddf8f358c58f6e92e3c9e/ADOPTERS.md?plain=1#L3

**Comment by FeynmanZhou** [comment]
@pdecat  Thanks for the feedback! Are you also using ORAS to manage OCI artifacts in the GitLab Container Registry?

**Comment by pdecat** [comment]
Yes, for Steampipe plugins.

FWIW, I'm currently porting Steampipe from github.com/deislabs/oras v0.9.0 to oras.land/oras-go/v2 v2.2.0, see https://github.com/turbot/steampipe/pull/3620/files

**Comment by dvgitit** [comment]
It looks like, GitLab on prem does not support devcontainer feature distribution (https://containers.dev/implementors/features-distribution/#oci-registry). Although described differently here https://docs.gitlab.com/ee/user/packages/container_registry/#supported-image-types. In this case, GirLab is not OCI conformant.

**Comment by TerryHowe** [comment]
I don't think this was attempting to document enterprise gitlab. I haven't used it in years, but I recall the on prem github was vastly different and very limited.
