### ISSUE TITLE
[Documentation Feedback]: Add GitLab registry's documentation

### ISSUE THREAD

**Issue by asmitbm** [oras-project/oras-www#197]
### Page URL

https://oras.land/docs/adopters#registries-supporting-oci-artifacts

### User feedback

Now that we have Gitlab as an adopter (#196 ), it would be nice to have basic ORAS CLI commands perfomed on GitLab Container Registry.

Example: https://oras.land/docs/adopters#github-packages-container-registry-ghcr

Cc: @FeynmanZhou @TerryHowe  @deepeshaburse

**Comment by asmitbm** [comment]
> @asmitbm Can I work on this issue

Sure, you can give it a try 👍🏼

**Comment by sambhavgupta0705** [comment]
@asmitbm it would be nice if you can guide me as I am very new to this community.
Like where can I find the docs to know more about it.

**Comment by sambhavgupta0705** [comment]
Thanks a lot @asmitbm 😄

**Comment by TerryHowe** [comment]
Done https://oras.land/adopters
