### ISSUE TITLE
Add example for "--resolve" flag

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#200]
### What is the version of your ORAS CLI

v1.0.0

### What would you like to be added?

There is a flag `--resolve host:port:address[:address_port]`  which is used to customize DNS for the registry, formatted in `host:port:address[:address_port]`. We need to add this example to ORAS commands with `--resolve` flag.

Giving an example:

```
oras login prod.registry.io:80 --resolve prod.registry.io:80:127.0.0.1:5000 --plain-http
```

### Why is this needed for ORAS?

Let users understand how to use the `--resolve` flag 

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by amands98** [comment]
This has not yet been resolved, I'll take care of it. // @FeynmanZhou @shizhMSFT @asmitbm
