### ISSUE TITLE
The readme.md file is too short and not good for introducing beginners to the repo

### ISSUE THREAD

**Issue by 1Shubham7** [oras-project/oras-www#211]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

the readme.md is affected. We can add a proper intro and these topics to the readme:
- get started
- How to contribute
- Join the community
- Licenses

### Additional comments?

I would love to work on this issue. Please assign it to me.

**Comment by asmitbm** [comment]
> the readme.md is affected. We can add a proper intro and these topics to the readme:
> 
> * get started
> * How to contribute
> * Join the community
> * Licenses
> 

Hi @1Shubham7,

Did you check the ORAS community page here? https://oras.land/docs/category/community
You can explore this and suggest changes as you see fit.

**Comment by 1Shubham7** [comment]
Yup, I checked it. should I not work on this issue ?

**Comment by TerryHowe** [comment]
We don't want to duplicate anything in the community page, but a link to that might be useful in the README. There might be a badge for license that could be added to the README, but I wouldn't add text about that. Try and keep the READMEs consistent with the main oras README https://github.com/oras-project/oras

**Comment by 1Shubham7** [comment]
ok. can you assign the issue to me ?
