### ISSUE TITLE
Update the documentation version from v1.0.0 to v1.1.0-rc.1

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#215]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

- [ ] The [installation guide](https://oras.land/docs/how_to_guides/installation/) is still v1.0.0. It needs to be changed to v1.1.0-rc.1
- [ ] Homebrew, Winget, Nix, and Snap only support ORAS v1.0.0 so far. The [installation guide](https://oras.land/docs/how_to_guides/installation/) should remind users that v1.1.0-rc.1 are not available on those package managers. They are still WIP or to be upgraded.
- [ ] There is a version number on the website. However, it's not appropriate to state that the whole ORAS project is using the same version as the ORAS CLI (e.g. v1.0.0). The ORAS libraries like ORAS-go, ORAS-py, and ORAS-dotnet have different versioning strategies, Should the version number need to be removed from the ORAS website or we state that this version number is the CLI version? 
![image](https://github.com/oras-project/oras-www/assets/40452856/d89b1323-5119-40a8-a598-bee6f8b3c8fd)

**Comment by deepeshaburse** [comment]
@FeynmanZhou I would like to work on this issue

**Comment by asmitbm** [comment]
@FeynmanZhou so should I create a dropdown containing different versions or should I remove v1.0.0 completely as of now?

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou so should I create a dropdown containing different versions or should I remove v1.0.0 completely as of now?

@asmitbm Please hold on to this change. I will confirm it with other ORAS maintainers for the version number change.

**Comment by TerryHowe** [comment]
Done
