### ISSUE TITLE
[Documentation Feedback]: wrong sentencing, errors and misspells in docs

### ISSUE THREAD

**Issue by 1Shubham7** [oras-project/oras-www#228]
### Page URL

https://oras.land/docs/how_to_guides/pushing_and_pulling

### User feedback

Found some misspells, errors and wrong sentencing in the docs, specially the [pushing and pulling](https://oras.land/docs/how_to_guides/pushing_and_pulling) part

![anotherissue](https://github.com/oras-project/oras-www/assets/116020663/6e995994-0253-42cb-8239-b816966fe8a5)
I think [OCI Artifacts][artifacts] should be a link, I guess its a markdown error.

![myissue](https://github.com/oras-project/oras-www/assets/116020663/07a1f4e2-f9ca-4c2f-a8b5-7c0b90a70162)

"Pushing single files involves referencing the unique artifact type and at least one file."  maintainers can better rephrase this sentence since they have more knowledge than me, I feel it should be "Pushing artifacts with single file involves referencing the unique artifact type and a file"

![anotherbug](https://github.com/oras-project/oras-www/assets/116020663/935d6334-c869-4649-a955-b738832fab62)

"oras should provides a solution" > "oras provides a solution". also the entire para is written in a very confusing way, can be improved

**Comment by FeynmanZhou** [comment]
Thanks @1Shubham7 for reporting it. I assigned this item to you.

**Comment by 1Shubham7** [comment]
Done @FeynmanZhou , Please check it out.
