### ISSUE TITLE
update version number in docusaurus.config file

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-www#260]
@qweeah @FeynmanZhou Since we are changing version numbers on the installation guide, I think we also need to change the version number in docusaurus.config file.

https://github.com/oras-project/oras-www/blob/56ad143b78bc5be5f2f223802613ae438b7e8c67/docusaurus.config.js#L60

_Originally posted by @asmitbm in https://github.com/oras-project/oras-www/pull/257#pullrequestreview-1611000582_

**Comment by asmitbm** [comment]
> https://github.com/oras-project/oras-www/blob/56ad143b78bc5be5f2f223802613ae438b7e8c67/docusaurus.config.js#L60

@qweeah We use this version number to tell users which version of the documentation they're looking at on our website. It's like a label to help them know what they're reading. 

If in future if ORAS do plan to maintain multiple versions of documentation then that will be useful. Additionally, we can explore the possibility of automatically extracting the latest version number from the docusaurus.config file and utilizing it as a variable throughout the documentation. This approach would eliminate the need to manually update version numbers across various sections.

**Comment by asmitbm** [comment]
Not closing this issue as of now to discuss the possibiliity of dynamic update of version numbers.

**Comment by TerryHowe** [comment]
I think what can be generated is now generated and we support at least two versions now. More if we wanted to.
