### ISSUE TITLE
Documentation Says to Follow Us on the Bird

### ISSUE THREAD

**Issue by TerryHowe** [oras-project/oras-www#269]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

Link in header recommends following us at https://twitter.com/orasproject instead of X

### Additional comments?

Change the icon and link

**Comment by pabitra0011** [comment]
I am new to open source, and I would like to motivate myself to contribute to a good first issue. Can you please assign me this issue?

**Comment by TerryHowe** [comment]
Done

**Comment by pabitra0011** [comment]
Thank you very much @TerryHowe sir.

Should I change both the Twitter page link and the icon, or just the icon?

**Comment by TerryHowe** [comment]
Probably both.
