### ISSUE TITLE
migrate to oras-go for credentials 

### ISSUE THREAD

**Issue by kranurag7** [oras-project/oras-www#276]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on oras.land is affected?

https://oras.land/docs/client_libraries/go#pull-an-image-using-the-docker-credential-store 

Given https://github.com/oras-project/oras-credentials-go is no longer stable and will only be used for experimental add-ons, we should switch to an example that uses oras-go library for authentication.

**Comment by TerryHowe** [comment]
I'm not seeing any references to oras-credentials-go in this project or oras-go
