### ISSUE TITLE
[Add adopter]: Helmper

### ISSUE THREAD

**Issue by ChristofferNissen** [oras-project/oras-www#307]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What is the name of your project/registry?

`helmper` is a go program that reads Helm Charts from remote OCI registries and pushes the charts container images to your registries with optional OS level vulnerability patching.

`helmper` is built with [Helm](<https://github.com/helm/helm>), [Oras](<https://github.com/oras-project/oras-go>), [Trivy](https://github.com/aquasecurity/trivy), [Copacetic](https://github.com/project-copacetic/copacetic) ([Buildkitd](https://github.com/moby/buildkitd)) and [Cosign](https://github.com/sigstore/cosign).

Helmper connects via gRPC to Trivy and Buildkit so you can run `helmper` without root privileges whereever you want. 

`helmper` demonstrates exceptional proficiency in operating within controlled environments that might require Change Management and/or air-gapped networks. This expertise is particularly beneficial in industries subject to stringent regulations, such as Medical and Banking. This is due to `helmper` ensures binary reproducibility of Helm Charts by storing all necessary artifacts in your registries.

`helmper` provides an interface to reduce the maintenance burden associated with managing a large collection of Helm Charts by:

- automatically detecting all enabled container images in charts
- providing an easy way to stay up to date on new chart releases
- providing option to only import new images, or all images
- enabling quick patching(and re-patching) of all images
- enabling signing of images was an integrated part of the process
- providing a mechanism to check requirements/dependencies before deploying charts with fx GitOps

I would love for Helmper to be listed on the Oras page to increase visibility for the project and to showcase what is possible when using the oras-go library in projects.

I am the maintainer of Helmper. Helmper has been donated to the community by my company, but they do not want to be officially mentioned in the project (Banking).

### Link of your project/registry

https://github.com/ChristofferNissen/helmper

### Link of your project's/registry's SVG

https://github.com/ChristofferNissen/helmper/blob/main/docs/logo/helmper.svg

**Comment by FeynmanZhou** [comment]
Hi @ChristofferNissen , thanks for sharing your use case! Would you mind raising a PR to add Helmper to ORAS adopters page?

**Comment by ChristofferNissen** [comment]
Hey @FeynmanZhou, thanks for maintaing such an awesome tool 🙌 Added a PR here: https://github.com/oras-project/oras-www/pull/318 but having some problems assigning this issue to the PR

**Comment by ChristofferNissen** [comment]
Had to open a new PR to correct the svg #320

**Comment by ChristofferNissen** [comment]
Cheers!
