### ISSUE TITLE
[Bug Report]: icons for Github/slack/X are missing 

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-www#347]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### Steps to reproduce the bug

- Visit oras.land
- The icons of Github/slack/X are not loaded on the top-right part

### Expected behavior

Should show icons

### Screenshots

![image](https://github.com/oras-project/oras-www/assets/4254263/cca00e69-b5fc-47ab-8743-725cee6fa4c3)

**Comment by TerryHowe** [comment]
The docusaurus update broke the link images https://github.com/oras-project/oras-www/pull/337/files

**Comment by asmitbm** [comment]
<img width="306" alt="Screenshot 2024-06-13 at 10 55 27 AM" src="https://github.com/oras-project/oras-www/assets/81866614/41ab09e3-7095-4d6b-b436-d3edf5df1a2e">

This is working fine locally as well as on Gitpod. Maybe we can clear the Netlify cache and redeploy the website again. That might fix the issue.

**Comment by FeynmanZhou** [comment]
This issue has been fixed in https://github.com/oras-project/oras-www/pull/364 so close it as completed
