### ISSUE TITLE
[Add adopter]:Red Hat Quay

### ISSUE THREAD

**Issue by BillDett** [oras-project/oras-www#380]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What is the name of your project/registry?

Red Hat Quay. Quay is available as an open source project, a Red Hat product and the hosted service quay.io. Quay is used by tens of thousands of Red Hat customers and open source community members to build, manage and scan their container images. We have recently introduced support for OCI Distribution 1.1 (including Referrers API) and are seeing a growing adoption of customers using Quay as a general artifact store. I am part of the Quay Engineering team at Red Hat.

### Link of your project/registry

https://github.com/quay/

### Link of your project's/registry's SVG

https://quay.io/repository/bdettelb/quaylogo?tab=tags

### Additional comments?

Authenticating to quay.io using a Robot Account and Token

`echo $TOKEN | oras login -u $ROBOT_ACCOUNT --password-stdin quay.io`

Pusing an artifact to quay.io

`oras push quay.io/$USER/$REPOSITORY/myartifact:v1 --artifact-type application/text ./myartifact.txt`

Pulling an artifact from quay.io

`oras pull quay.io/$USER/$REPOSITORY/myartifact:v1`

**Comment by TerryHowe** [comment]
@sabre1041 any comment?

**Comment by sabre1041** [comment]
> @sabre1041 any comment?

As described within this PR, Quay supports the use of OCI artifacts and it is documented in their [project overview](https://docs.projectquay.io/quay_io.html).

**Comment by TerryHowe** [comment]
Would you create a PR @BillDett ?

**Comment by asmitbm** [comment]
I can help with this
