### ISSUE TITLE
[Add adopter]: Score

### ISSUE THREAD

**Issue by mathieu-benoit** [oras-project/oras-www#409]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### What is the name of your project?

Score (CNCF Sandbox): https://www.cncf.io/projects/score/ is a developer-centric and platform-agnostic workload specification. It ensures consistent configuration between local and remote environments.

`score-go` is a common library used by Score implementations such as `score-compose` and `score-k8s`. `score-go` just added the ability to import additional provisioners files stored as OCI image in addition to `git`, `http(s)`, etc.

Score end users can now easily run this commands to import their own library of provisioners:
```
score-compose init --provisioners oci://ghcr.io/score-spec/score-compose-community-provisioners:v0.1.0#00-service.provisioners.yaml

score-k8s init --provisioners oci://ghcr.io/score-spec/score-k8s-community-provisioners:v0.1.0#00-service.provisioners.yaml
```

### Link of your project

- `score-go` library: https://github.com/score-spec/score-go
- `score-compose` implementation: https://github.com/score-spec/score-compose
- `score-k8s` implementation: https://github.com/score-spec/score-k8s

### Link of your project's SVG

https://github.com/cncf/artwork/blob/main/projects/score/icon/color/score-icon-color.svg

**Comment by TerryHowe** [comment]
Thanks!
