### ISSUE TITLE
[Bug Report]: Marquee gap

### ISSUE THREAD

**Issue by TenzDelek** [oras-project/oras-www#424]
### Code of Conduct

- [X] I have read and agree to the ORAS' [Code of Conduct](https://github.com/oras-project/oras-www/blob/main/CODE_OF_CONDUCT.md)

### Steps to reproduce the bug

go to homepage 
scroll down to collaboration section

### Expected behavior

the marquee movement should be continues , where end is followed by head. currently there is a reload happening after the last icon is shown

### Screenshots

<img width="1228" alt="image" src="https://github.com/user-attachments/assets/6a780f87-78dc-4631-be5b-30a2fae30aa1">

### Additional context?

NA

**Comment by TenzDelek** [comment]
how does the raising pr work here? do we wait for the approval from a maintainer or directly raise a pr? cc @FeynmanZhou

**Comment by TerryHowe** [comment]
For CNCF projects you need to signoff your commits like `git commit -s ...` and that you agree to the DCO https://github.com/cncf/foundation/blob/main/dco-guidelines.md

My JS skills are pretty poor, so a PR would be much appreciated.
