### ISSUE TITLE
Introduce the mkdocs-markdownextradata-plugin

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#47]
To avoid the manual maintenance like updating the version number in ORAS documentation, we can introduce the [mkdocs-markdownextradata-plugin](https://github.com/rosscdh/mkdocs-markdownextradata-plugin) to help us injects the mkdocs.yml extra variables into the markdown template. Then we can use global variables to update the ORAS documentation efficiently. 

This proposal is recommended by @vsoch , we want to adopt and apply this plugin in this repository.

**Comment by TerryHowe** [comment]
Maybe skip this and do the Hugo migration. Hugo has a drop down for releases

**Comment by asmitbm** [comment]
Closing this as we have a new website framework.
