### ISSUE TITLE
Document oras copy

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras-www#48]
The latest release of oras provides `oras copy`, enabling a graph of artifacts, and its supply chain references to be copied across any ORAS Artifact enabled registry.
As OCI Artifacts merges, ORAS will add support as well.

This item tracks adding `oras copy` cli docs, summarizing the experience in the https://oras.land/cli/

**Comment by FeynmanZhou** [comment]
Copied. I also create a separate issue to track the documentation updates.

**Comment by TerryHowe** [comment]
https://oras.land/cli_reference/4_oras_copy/ close this?
