### ISSUE TITLE
Update the documentation to v0.14.0

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#49]
ORAS CLI v0.14.0 was released on Aug 21. The documentation should be updated to align with the latest version. I listed the p1 documents that need to be updated first. 

- [ ] ORAS copy: https://github.com/oras-project/oras-www/issues/48
- [ ] ORAS attach
- [ ] ORAS manifest fetch
- [ ] ORAS discovery
- [ ] New options for `oras push` and `oras pull`

**Comment by TerryHowe** [comment]
Close this issue, it is done
