### ISSUE TITLE
Fix the Netlify build

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras-www#5]
Something is wrong, not sure if related to Netlify account or Python/Poetry/Mkdocs

**Comment by bridgetkromhout** [comment]
Looks like a Python issue, from the netlify logs:

• Installing mkdocs-material (7.1.4)
2:43:05 AM: Traceback (most recent call last):
2:43:05 AM:   File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
2:43:05 AM:     sys.exit(cli())
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
2:43:05 AM:     return self.main(*args, **kwargs)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1059, in main
2:43:05 AM:     rv = self.invoke(ctx)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
2:43:05 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
2:43:05 AM:     return ctx.invoke(self.callback, **ctx.params)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 767, in invoke
2:43:05 AM:     return __callback(*args, **kwargs)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
2:43:05 AM:     build.build(config.load_config(**kwargs), dirty=not clean)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 197, in load_config
2:43:05 AM:     errors, warnings = cfg.validate()
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 107, in validate
2:43:05 AM:     run_failed, run_warnings = self._validate()
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/base.py", line 62, in _validate
2:43:05 AM:     self[key] = config_option.validate(value)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 131, in validate
2:43:05 AM:     return self.run_validation(value)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 609, in run_validation
2:43:05 AM:     plgins[item] = self.load_plugin(item, cfg)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 617, in load_plugin
2:43:05 AM:     Plugin = self.installed_plugins[name].load()
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2228, in load
2:43:05 AM:     self.require(*args, **kwargs)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2245, in require
2:43:05 AM:     items = working_set.resolve(reqs, env, installer)
2:43:05 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
2:43:05 AM:     raise DistributionNotFound(req, requirers)
2:43:05 AM: pkg_resources.DistributionNotFound: The 'typing-extensions>=3.7.4.0; python_version < "3.8"' distribution was not found and is required by GitPython

**Comment by jdolitsky** [comment]
Fixed via https://github.com/oras-project/oras-www/commit/7629bd2455c8a7fc7bd935218c3219754e11eac3
