### ISSUE TITLE
Migrate to updated Ubuntu base image for Netlify build

### ISSUE THREAD

**Issue by bridgetkromhout** [oras-project/oras-www#56]
We need to migrate the Netlify builds from Ubuntu 16.04 to Ubuntu 20.04. I ran [Netlify's recommended migration test](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239#how-can-i-run-a-test-build-with-the-new-image-6) and it failed as seen in https://app.netlify.com/sites/oras-project/deploys/632e213fb515e86327a322b3.

It looks like we need to adjust the way we call python:

```
4:12:33 PM: Building without cache
4:12:33 PM: Starting to prepare the repo for build
4:12:33 PM: No cached dependencies found. Cloning fresh repo
4:12:33 PM: git clone https://github.com/oras-project/oras-www
4:12:33 PM: Preparing Git Reference refs/heads/main
4:12:34 PM: Parsing package.json dependencies
4:12:34 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'site' versus '/' in the Netlify UI
4:12:34 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'pip3 install --upgrade pip
pip3 install -r requirements.txt &&
mkdocs build -d site
' versus '' in the Netlify UI
4:12:34 PM: Starting build script
4:12:34 PM: Installing dependencies
4:12:34 PM: /opt/build-bin/run-build-functions.sh: line 223: /opt/buildhome/python3.7/bin/activate: No such file or directory
4:12:34 PM: Error setting python version from runtime.txt
4:12:34 PM: Please see https://github.com/netlify/build-image/blob/focal/included_software.md for current versions
4:12:34 PM: Build was terminated: Build script returned non-zero exit code: 1
4:12:34 PM: Creating deploy upload records
4:12:34 PM: Failing build: Failed to build site
4:12:34 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1 (https://ntl.fyi/exit-code-1)
4:12:34 PM: Finished processing build request in 1.941969947s
```

I'm out of time to test further today, but figured I should note this here for transparency/in case someone wants to take it up. We have a little time but should get this sorted out.

**Comment by vsoch** [comment]
I think likely ubuntu 20.04 has Python 3.8, and perhaps they don't support below that version? We have Python 3.7 as the default, which is set in our runtime.txt. To debug I would do a tree / ls to see what is in our buildhome for python.

**Comment by FeynmanZhou** [comment]
@bridgetkromhout This issue doesn't impact the Netlify functions. I can help to upgrade the build server but it seems it requires Netlify access. Do you know who can invite me to the ORAS Netlify account?

**Comment by nate-double-u** [comment]
I'd be happy to help, but I'm not a team member on the oras-project netlify team either. I'm checking if anyone else at the CNCF does.

**Comment by TerryHowe** [comment]
The project is running python 3.8 now. This issue is either resolved or should be.

**Comment by nate-double-u** [comment]
> The project is running python 3.8 now. This issue is either resolved or should be.

I confirm the build image has been updated.
<img width="1276" alt="Screenshot 2023-02-10 at 2 23 27 PM" src="https://user-images.githubusercontent.com/4453979/218210424-0e1d6d18-a3f0-423a-b487-7b6d7027d7af.png">
