### ISSUE TITLE
re-submit documentation for cache usage with CLA

### ISSUE THREAD

**Issue by bridgetkromhout** [oras-project/oras-www#6]
Hi, @LucianBuzzo - Your PR https://github.com/oras-project/oras-www/pull/1 was merged before we had the CLA bot on this repo. For this reason, I am reverting it in https://github.com/oras-project/oras-www/pull/7.

Will you please re-submit this PR so we can have the CLA bot run the check? Then we can merge your new PR with the same content.

Apologies for the extra step.

**Comment by LucianBuzzo** [comment]
Hi @bridgetkromhout what is the CLA bot?

**Comment by bridgetkromhout** [comment]
Thanks, @LucianBuzzo! And sorry, I should have explained more clearly. The CLA is explained here: https://cla.opensource.microsoft.com/
