### ISSUE TITLE
Publish docs for oras copy

### ISSUE THREAD

**Issue by SteveLasker** [oras-project/oras-www#63]
### What is the version of your ORAS CLI

v0.15.0

### What would you like to be added?

Documentation to oras.land for how to use `oras copy`, providing links from external sources.

### Why is this needed for ORAS?

Usability and documentation from external articles.

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by shashankiitbhu** [comment]
Hi @SteveLasker, I am Interested in solving this task, can you assign this to me?

**Comment by asmitbm** [comment]
> Hi @SteveLasker, I am Interested in solving this task, can you assign this to me?

Hi @shashankiitbhu 

I think this issue is stale because docs for `oras copy` already exists. Check the link here: https://oras.land/docs/CLI_Reference/oras_copy

Cc: @FeynmanZhou

**Comment by TerryHowe** [comment]
This is done. Command documentation used to be very sparse.
