### ISSUE TITLE
Refactor the ORAS documentation structure and write new user guides

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#65]
This issue relates to a proposal for a [LFX mentorship project](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug) for Term 2, 2023.  Please feel free to comment on this issue about your interest and willingness, but note that commenting here is not the same as applying to LFX.

- Description: Refactor the ORAS documentation structure and write new user guides based on the latest version of ORAS.
- Expected Outcome: Deliver a developer-friendly documentation structure for ORAS and write new user guides according to the proposed documentation structure
- Recommended Skills: OCI, Docker, ORAS, Markdown
- Mentor(s): Mentor(s): Terry Howe (@TerryHowe , terrylhowe@gmail.com), Asmit Malakannawar (@asmitbm , asmitbm2952002@gmail.com), Feynman Zhou (@FeynmanZhou , feynmanzhou@microsoft.com)

The detailed ORAS documentation structure and content should be refactored and updated to the latest version of ORAS. I would like to propose the new documentation structure as follows.

Chapters | Documents | Status | Need to review and update existing docs? | Refreshing
-- | -- | -- | -- | --
Overview of ORAS | - What is ORAS   <br> - Use cases  <br>  - Demos   <br>  - Roadmap | 2/4 | Yes | Per each new release.   Maintained by @oras-project/oras-client-release-managers 
Installation | Install ORAS CLI   on multiple platforms | 1/1 | Yes | Per each new release
Getting Started | ORAS CLI quick start | 0 |   | Per each new release
CLI Guides | - Authentication (login and logout)  <br>   - Pull and push artifacts    <br>   - Attach files to artifacts     <br>  - Copy artifacts across registries    <br>   - Discover referrers of a manifest    <br>   - Repository and tag operations   <br>    - Manifest and blob operations | 3/7 | Yes | Per each new release
How-to guides | - Using   ORAS in Secure Supply Chain <br>  - Using   ORAS in CI/CD (e.g. GitHub Actions) <br>  -   Working with OCI Registries  <br> - Using   ORAS with Kubernetes manifest | 1/4 | Yes | Per each new release and E2E scenario
Development and contribution |<br> - How to build ORAS CLI <br>   - Add a new command and flag  <br>  - CLI release process | 2/3 | Yes | Maintained by developers
Client Library | - Overview   <br>  - Golang library guide   <br>  - API reference  <br>   - Python library guide |   | Yes | Maintained by   library developers
CLI Reference | This part of the content will be generated from the source code of CLI help documentation. | 0 | No | Maintained by   developers and @oras-project/oras-client-release-managers
Glossary | Concepts and terms | 0 | No | Per each new term and feature
FAQ and Troubleshooting |   | 0 | No | According to user questions. Maintained by @oras-project/oras-client-release-managers

**Comment by TerryHowe** [comment]
![Screen Shot 2023-02-02 at 15 52 17](https://user-images.githubusercontent.com/104113/216469320-08bfe82d-6b5b-4c2e-a476-a28e16df44ff.png)

A familiar format maybe? I think some of the topics you mentioned would be subtopics of this for example troubleshooting would be in tasks.

I think the hugo migration should be first though.

**Comment by Ananya2003Gupta** [comment]
I am interested in working on this issue and contributing to ORAS documentation. I have few doubts and ideas in mind, but I am unable to join the slack workspace. I have commented about the same problem in https://github.com/oras-project/oras-www/issues/158#issuecomment-1543643533
Kindly let me know, where can I communicate further for this issue.
Best,
Ananya Gupta

**Comment by Ananya2003Gupta** [comment]
> ![Screen Shot 2023-02-02 at 15 52 17](https://user-images.githubusercontent.com/104113/216469320-08bfe82d-6b5b-4c2e-a476-a28e16df44ff.png)
> 
> A familiar format maybe? I think some of the topics you mentioned would be subtopics of this for example troubleshooting would be in tasks.
> 
> I think the hugo migration should be first though.

I find Meshery's Docs (docs.meshery.io) to be quite detailed and developer friendly. I feel ORAS Docs can be structured in a similar fashion with more in depth knowledge of features mentioned in the issue. The docs can be made interactive by incorporating mock up of ORAS CLI in them (if possible to do so).

**Comment by octonawish-akcodes** [comment]
I am interested in this.

**Comment by asmitbm** [comment]
> I am interested in this.

Hi @octonawish-akcodes 

You can join the Slack channel, with the provided link on the [website](https://oras.land/). If that doesn't work, you can join the [CNCF Slack](https://cloud-native.slack.com/) and then navigate to the `#oras` channel. Say hi and introduce yourself :)

**Comment by Roseline-Bassey** [comment]
Hey, Mentors @TerryHowe , @asmitbm , @FeynmanZhou. My name is Roseline and I'm interested in contributing to this project.

**Comment by shashankiitbhu** [comment]
Hey Mentors @asmitbm @TerryHowe @FeynmanZhou . My name is Shashank Kumar and I am interested in contributing to this project.

**Comment by yash7raut** [comment]
> > I am interested in this.
> 
> Hi @octonawish-akcodes
> 
> You can join the Slack channel, with the provided link on the [website](https://oras.land/). If that doesn't work, you can join the [CNCF Slack](https://cloud-native.slack.com/) and then navigate to the `#oras` channel. Say hi and introduce yourself :)

@asmitbm I am unable to join the Slack channel.

**Comment by asmitbm** [comment]
> @asmitbm I am unable to join the Slack channel.

Hi @yash7raut,

You can use this link: https://communityinviter.com/apps/cloud-native/cncf

**Comment by yash7raut** [comment]
Thank you for the link @asmitbm.

What should be my next steps?

I am exploring the repository and trying to familiarize myself with the project.

**Comment by Vikash-8090-Yadav** [comment]
Hey Mentors @asmitbm @TerryHowe @FeynmanZhou . My name is Vikash Kumar Yadav  and I am very myuch interested in contributing to this project. Can u please suggest me any first  contributor issue?

**Comment by ayush4345** [comment]
Hey, can anyone tell me the deadline for applying to this mentorship?

**Comment by asmitbm** [comment]
> Hey, can anyone tell me the deadline for applying to this mentorship?

Deadline to apply is May 23rd 5PM PDT.

**Comment by TerryHowe** [comment]
Done.
