### ISSUE TITLE
Provide instruction to validate the checksum of ORAS CLI binaries

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#69]
ORAS release uses a GPG key to sign each release binaries in the [release](https://oras.land/cli/5_developer_guide/#release-checklist) process. We should provide instructions to help users validate the checksum of ORAS CLI binaries.

**Comment by aryab2003** [comment]
I am willing to work under this project.Could you please provide me the details about this issue?

**Comment by FeynmanZhou** [comment]
@aryab2003 Thanks for your interest. However, this issue has been assigned to @deepeshaburse as she is the mentee of the LFX mentorship program.

**Comment by FeynmanZhou** [comment]
@deepeshaburse 
According to the v1.0.0 release notes, it mentioned the GPG key as follows:

> This release was signed with BE6F A8DD A48D 4C23 0091 A0A9 276D 8A72 4CE1 C704 (@qweeah's GPG key) which can be found [here](https://github.com/qweeah.gpg).

So it has the following steps to validate the release binary using GPG. You can try it locally:

```
gpg --import https://github.com/shizhMSFT.gpg // save it to a local `.gpg` file

gpg --gen-key

sign

save

gpg --edit-key Shiwei trust

choose "4 = I trust fully"

gpg --verify oras_1.0.0_linux_amd64.tar.gz.asc oras_1.0.0_linux_amd64.tar.gz
```

**Comment by deepeshaburse** [comment]
@FeynmanZhou thanks for the input!
