### ISSUE TITLE
add example for using oras CLI container as locally installed application

### ISSUE THREAD

**Issue by qweeah** [oras-project/oras-www#70]
In current [documentation](https://oras.land/cli/#:~:text=%5C%3B%25PATH%25-,Docker%20Image,-A%20public%20Docker), there is an example of using oras container as locally installed application.

> docker run -it --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.16.0 help

We can remove `-v $(pwd):/workspace` since `oras help` won't use it, and add more examples like `push` or `pull` to show amazing work oras container can do with mounting.

**Comment by qweeah** [comment]
cc @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Thanks. I will create a PR to update the whole installation guide. 
@qweeah Can you clarify why we need to add examples like `push` or `pull` to the installation guide?

**Comment by qweeah** [comment]
I didn't mean we should add `push` and `pull` to the installation guide. They should be added to an ad-hoc doc to show how oras container can be used just like a locally installed application.
