### ISSUE TITLE
Create a quick start guide for using ORAS CLI to distribute OCI artifact

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#71]
ORAS CLI 0.16 has supported distributing OCI artifact manifest to any OCI-compatible registries. We need to create a quick start guide for using ORAS CLI to distribute the OCI artifact to the OCI registries.

[Zot](https://github.com/project-zot/zot) is a production-ready vendor-neutral OCI-native container image registry (purely based on OCI Distribution Specification). We plan to use the Zot registry in this guide to demonstrate OCI artifact use cases with ORAS.

**Comment by rchincha** [comment]
👍 

If it helps, oras already part of zot ci
https://github.com/project-zot/zot/blob/main/test/blackbox/pushpull.bats#L103
(^ mostly bash scripting!)

**Comment by nishchay-veer** [comment]
Hey @FeynmanZhou , can I work on this issue ?
