### ISSUE TITLE
Develop a new website for ORAS

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#82]
ORAS only has a documentation site so far, we want to develop a new website using the [Hugo framework](https://gohugo.io/) based on the Figma layout design. It will replace the existing [ORAS documentation site](https://oras.land/) and provide a better user experience with interactive design. We will provide a new Figma design for the website soon.

This issue is open for the [CNCF LFX Mentorship 2023 program](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May). If you are interested in implementing this issue, please let us know.

**Comment by hamees-sayed** [comment]
Hello, I'm interested in working on this issue for the LFX Mentorship term.

**Comment by codewarsfx** [comment]
hi Im interested in working on this issue

**Comment by Asmit2952** [comment]
Hey, I am interested in working on this issue for LFX Mentorship 2023!

**Comment by TerryHowe** [comment]
Whomever does this, I can provide some help on the Hugo migration which should probably be the first step.

**Comment by Asmit2952** [comment]
I wanted to discuss a few ideas with the maintainers before submitting the final proposal. Can anyone guide me in that?

**Comment by Rishikavishnoi** [comment]
Hello, I'm interested in working on this issue for the LFX Mentorship 2023 term...!

**Comment by jakada01** [comment]
Hello, This project seems really interesting. I would like to work on this project for the LFX Mentorship 2023 term.

**Comment by horizenight** [comment]
Hey This is a very cool Project . Excited to be a part of the LFX Mentorship Term.

**Comment by akshatvirmani** [comment]
Hi! I am interested in working on this issue under LFX Mentorship!

**Comment by YashhKamboj** [comment]
Hey, I am interested in working on this issue for LFX Mentorship 2023!

**Comment by YashKamboj** [comment]
Hey, I am interested in working on this issue for LFX Mentorship 2023!

**Comment by FeynmanZhou** [comment]
Hi folks, @horizenight @YashKamboj @akshatvirmani @jakada01 @Rishikavishnoi @Asmit2952 @codewarsfx @hamees-sayed 

Thanks for your interest in this project! Now you can apply for this project on https://mentorship.lfx.linuxfoundation.org/project/7f633ade-64f5-477c-bcbe-7b6693329c63

**Comment by FeynmanZhou** [comment]
@TerryHowe Really appreciate your help and willingness! You will be a great mentor.

**Comment by jakada01** [comment]
I applied for the program and submitted the prerequisite tasks. Ready to start...!

**Comment by ConnectBhawna** [comment]
Hi @TerryHowe @FeynmanZhou , I am interested in learning about this project and want to work on this project under LFX Mentorship.
Please let me know about any materials or resources that I should learn to get a better understanding of the project and its requirements.

Additionally, I was wondering if there is anything else I can do to get started, such as research and learn about the project from the existing documentation.

**Comment by Mr-DG-Wick** [comment]
Hey mentors, I am incredibly enthusiastic at the prospect of working as an LFX mentee under ORAS. As a driven individual with a passion for learning and growing in the field of technology, I see this mentorship as an exceptional chance to gain valuable knowledge and experience.

I've already completed the pre-requisites for the application, and as next steps, I am now reviewing the documentation. I hope to start contributing on some issues soon. Excited to learn more! (ps: if you'd like to learn more about me, here's my [corner](https://mr-dg-wick.github.io/) of internet)

**Comment by Idadelveloper** [comment]
@FeynmanZhou I am very interested in implementing this

**Comment by akankshat05** [comment]
Hello @FeynmanZhou I am interested in working on this issue for LFX Mentorship 2023.

**Comment by shruti1421** [comment]
Hey @FeynmanZhou @TerryHowe, I'm really interested to contribute to this project want to work on this project under LFX Mentorship.

**Comment by aryans1319** [comment]
Hey, @FeynmanZhou I would love to work on this project under the LFX Mentorship program, I have the pre-requisite skills required for this and also have experience with the same, I have been going through the Hugo Docs recently as it's new to me but I believe it would be great to work with!

I have already completed the pre-requisites for the application, looking forward to learning and contributing more in developing the website with clean ui/ux as I believe the cleaner it is the better the reader feels and wants to go through it

**Comment by Oms-343** [comment]
> Whomever does this, I can provide some help on the Hugo migration which should probably be the first step.

 @TerryHowe yeah, I have limited idea about the mkDocs framework with which the documentation was built at the first place. A quick  migration guide will definitely serve as a booster.

**Comment by Oms-343** [comment]
So we basically  have to build a completely new documentation site using Hugo framework and thus terminate the existing site which was build with mkDocs right..?

**Comment by Aryamanz29** [comment]
Hi @FeynmanZhou, I'm thrilled to be part of this project. I have already had good experience with static site generator frameworks like Hugo, Sphinx, and Docusaurus in building technical documentation sites. I've developed and customised various documentation sites in the past for open-source projects. I'm currently reviewing the ORAS documentation and am eager to tackle some exciting issues for this project. I'm excited to both learn from and contribute to this project.

**Comment by monalisha31** [comment]
This project is quite interesting and i have applied through LFX mentorship program.  Looking forward to your response.

**Comment by RajGM** [comment]
Hi @FeynmanZhou  
Can we apply as a mentor for this project as well?

**Comment by robin025** [comment]
Hi @FeynmanZhou,

My name is Robin Singh, and I am a graduate student currently enrolled in the Master's Degree program at the University of Massachusetts. I am interested in working on this issue, and I am excited to contribute through the LFX program. Based on my understanding of the description, the objective of the project is to develop a new website for ORAS using the Hugo framework and a Figma layout design, which will replace the existing documentation site and provide a better user experience with interactive design. Is that correct?

Moreover, I am eager to participate in this project and will definitely be submitting an application. Thank you for considering my interest.

**Comment by Oms-343** [comment]
when is the last date to submit cover letter and resume..?

**Comment by ShravaniAK** [comment]
Hello @FeynmanZhou ,

I came across your open issue to develop a new website using the Hugo framework based on the Figma layout design, and I would like to express my interest in working on it.

I have experience with developing websites using the Hugo framework and creating interactive designs. I believe I can provide a better user experience for your documentation site, as I am committed to delivering high-quality work and meeting deadlines.

I am excited about the opportunity to contribute to the CNCF LFX Mentorship 2023 program and work with the ORAS team. Please let me know if there are any additional details that I should know about this project, and I would be happy to discuss further.

Thank you for considering my application. I look forward to hearing back from you.

**Comment by rajatverma311201** [comment]
Hello @FeynmanZhou I would like to contribute to this project, I am a full stack javascript developer (MERN Stack) and i am also familiar with NextJS, React Native etc.  I have applied in the LFX program
