### ISSUE TITLE
Fix routing in mkdocs

### ISSUE THREAD

**Issue by jdolitsky** [oras-project/oras-www#9]
In order to get table of contents for each subsection in a proper order, we are prefixing file names with numbers (e.g. `0_file.md`). This is reflected in the routes in the browser.

There is probably a configuration option to get custom route names: https://www.mkdocs.org/user-guide/configuration/

**Comment by TerryHowe** [comment]
If the migration to Hugo happens, this would be handled by `weight` in the header.

**Comment by nishchay-veer** [comment]
Hey @jdolitsky can I work on this issue ?
