### ISSUE TITLE
Irregular behavior when clicked on sidebar Oras go link

### ISSUE THREAD

**Issue by horizenight** [oras-project/oras-www#98]
*Describe the bug* 
When clicked on Oras go button on Sidebar it redirects to the GitHub Repository 

Expected Behaviour:
The link should generate a text that is a link to the repo so that the repo opens in a new tab .

https://user-images.githubusercontent.com/76839614/216815244-7c63a24e-1cd6-4ef7-b615-52fa98239e61.mp4

**Comment by shizhMSFT** [comment]
> @shizhMSFT Can you transfer this issue to the ORAS-WWW repo as it will be fixed in that repo?

Done 🆗

**Comment by shizhMSFT** [comment]
Current redirect is done by https://github.com/oras-project/oras-www/blob/main/docs/custom/main.html

**Comment by TerryHowe** [comment]
Maybe with the netify configuration you wouldn't actually need the files and then they wouldn't show up in the nav

**Comment by Amishakumari544** [comment]
we need to create a `_redirect`  file or we need to do the configuartion in the `netlify.toml`

**Comment by asmitbm** [comment]
Closing this as we have adopted new documentation framework.
