### ISSUE TITLE
Creating oras-project readme

### ISSUE THREAD

**Issue by Sukriti-sood** [oras-project/oras-www#99]
This feature provides newcomers with brief information about the organization's profile. ([Relative Link](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#organization-profile-readmes))

![Customizing-your-organization-s-profile-GitHub-Docs](https://user-images.githubusercontent.com/55010599/217823672-eb628719-b6d1-49ef-ac2f-cd13ccf5ec86.png)

I would like work on this issue for creating profile readme and creating organisation wide [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

Please create a `.github` repo if you find this feature relevant.

@FeynmanZhou

**Comment by TerryHowe** [comment]
Not doing.
